@baseUrl = {{baseUrl}}
@orgId = eb1e44e7-ff61-4d5e-bf1e-d8a0cac01753
@authToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb25faWQiOiJlYjFlNDRlNy1mZjYxLTRkNWUtYmYxZS1kOGEwY2FjMDE3NTMiLCJ1c2VyX2lkIjoiOTJhMmFmN2YtMDFiZi00ZGUyLWJkN2EtNjVkNjdkNTM4N2U2Iiwic3ViIjoiOTJhMmFmN2YtMDFiZi00ZGUyLWJkN2EtNjVkNjdkNTM4N2U2IiwiZW1haWwiOiJwYXNjaGFsaWRpLmNocmlzK2F1dGhAZ21haWwuY29tIiwiZXhwIjoxNzM1NTUyMzMwLCJpYXQiOjE3MzUxMjAzMzB9.gqnee7-zA12i83ta93xFno3Eqfjt0Me_J9p-TdnlviA
@apiKey = sk_28b83d06-0ca1-4c19-bdcb-9c315d67079c

### Base Routes
GET {{baseUrl}}/health

###
GET {{baseUrl}}/ws/chat/:room_id

##########################################
##########################################
##########################################
### Auth Routes
##########################################
##########################################
##########################################
POST {{baseUrl}}/api/organization_accounts/create
Content-Type: application/json

{
  "email": "paschalidi.chris+auth@gmail.com",
  "password": "paschalidi.chris+auth@gmail.com",
  "organization_name": "Test Org"
}

###
POST {{baseUrl}}/api/organization_accounts/sign-in
Content-Type: application/json

{
  "email": "paschalidi.chris+auth@gmail.com",
  "password": "paschalidi.chris+auth@gmail.com"
}

##########################################
##########################################
##########################################
### Organization Routes - Participants
##########################################
##########################################
##########################################
POST {{baseUrl}}/api/organizations/{{orgId}}/participants
X-API-Key: {{apiKey}}
Content-Type: application/json

{
  "name": "John Doe"
}

###
GET {{baseUrl}}/api/organizations/{{orgId}}/participants/count
Authorization: Bearer {{authToken}}

##########################################
##########################################
##########################################
### Organization Routes - Channels
##########################################
##########################################
##########################################
GET {{baseUrl}}/api/organizations/{{orgId}}/channels
X-API-Key: {{apiKey}}

### create a channel
POST {{baseUrl}}/api/organizations/{{orgId}}/channels
X-API-Key: {{apiKey}}
Content-Type: application/json

{
  "name": "uk"
}

###
GET {{baseUrl}}/api/organizations/{{orgId}}/channels/982aa74a-259b-42c1-b4b5-06b0ba1d3972
X-API-Key: {{apiKey}}

##########################################
##########################################
##########################################
### Organization Routes - Messages
##########################################
##########################################
##########################################
GET {{baseUrl}}/api/organizations/{{orgId}}/messages/982aa74a-259b-42c1-b4b5-06b0ba1d3972
X-API-Key: {{apiKey}}

###
POST {{baseUrl}}/api/organizations/{{orgId}}/messages
X-API-Key: {{apiKey}}
Content-Type: application/json

{
  "channel_name": "general",
  "participant_id": "e5f18559-5801-4a8f-96f9-6226316e2748",
  "content": "Hello world"
}

##########################################
##########################################
##########################################
### Admin Routes - Users
##########################################
##########################################
##########################################
GET {{baseUrl}}/api/organizations/{{orgId}}/users
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/organizations/{{orgId}}/users/count
Authorization: Bearer {{authToken}}

##########################################
##########################################
##########################################
### Admin Routes - API Keys
##########################################
##########################################
##########################################
POST {{baseUrl}}/api/organizations/{{orgId}}/generate-api-key
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/organizations/{{orgId}}/keys
Authorization: Bearer {{authToken}}

###
DELETE {{baseUrl}}/api/organizations/{{orgId}}/keys/:key_id
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/organizations/{{orgId}}/keys/count
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/api/organizations/{{orgId}}/keys
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "API Key 1",
  "key_type": "ReadWrite"
}