@baseUrl = {{baseUrl}}

### POST create participant with name
POST {{baseUrl}}/api/participants
Content-Type: application/json

{
  "name": "yo-nemae"
}


### POST create channel with name
POST {{baseUrl}}/api/channels
Content-Type: application/json

{
  "name": "yoyoo"
}

### GET channel by id
GET {{baseUrl}}/api/channels/efdd57bd-c852-43a0-8ddd-0c2894e50c05
Accept: application/json

### GET all channgels
GET {{baseUrl}}/api/channels
Accept: application/json
